use proc_macro2::TokenStream;
use quote::quote;
use syn::{Attribute, Data, DeriveInput, Fields, Ident};

use crate::parse::{ImportInput, ShapeExpr, ShapeInput, ShapeNode};
use crate::state::{
    FieldDef, TypeEntry, lookup, lookup_exported, next_anon_id, register, register_exported,
};

// ---------------------------------------------------------------------------
// Crate-scoped registry key
// ---------------------------------------------------------------------------

fn crate_key() -> Option<String> {
    std::env::var("CARGO_MANIFEST_DIR").ok()
}

// ---------------------------------------------------------------------------
// Generics helpers
// ---------------------------------------------------------------------------

/// Re-parse stored generics/where strings back into `syn::Generics`.
fn parse_stored_generics(entry: &TypeEntry) -> syn::Generics {
    if !entry.is_generic() {
        return syn::Generics::default();
    }
    let src = format!(
        "struct __D{} {} {{}}",
        entry.generics_tokens, entry.where_tokens
    );
    syn::parse_str::<DeriveInput>(&src)
        .map(|di| di.generics)
        .unwrap_or_default()
}

/// Determine the effective generics to use for a generated type.
///
/// Priority:
///   1. User-supplied `explicit` generics (non-empty) — honour exactly.
///   2. Source entry's registered generics (auto-inherit, only for anonymous intermediates).
///   3. Empty generics (non-generic type).
fn effective_generics(
    explicit: &syn::Generics,
    source_entry: &TypeEntry,
    allow_inherit: bool,
) -> syn::Generics {
    if !explicit.params.is_empty() || explicit.where_clause.is_some() {
        explicit.clone()
    } else if allow_inherit && source_entry.is_generic() {
        parse_stored_generics(source_entry)
    } else {
        syn::Generics::default()
    }
}

/// Returns a compile error when a source type is generic but the target declaration
/// provides no explicit generic parameters.
///
/// Only applied when `allow_inherit = false` (top-level `typex!` invocations).
/// Anonymous intermediates generated by composed expressions are exempt.
fn check_no_implicit_generics(
    source_ident: &Ident,
    source_entry: &TypeEntry,
    target_generics: &syn::Generics,
) -> Option<TokenStream> {
    if source_entry.is_generic()
        && target_generics.params.is_empty()
        && target_generics.where_clause.is_none()
    {
        Some(
            syn::Error::new(
                source_ident.span(),
                format!(
                    "type `{src}` has generic parameters; \
                     declare them explicitly in `typex!`, \
                     e.g. `Target<T> = {src}<T>`",
                    src = source_ident,
                ),
            )
            .to_compile_error(),
        )
    } else {
        None
    }
}

/// Split generics into the three parts needed for code generation:
/// `(impl_generics, ty_generics, where_clause)` as `TokenStream`s.
fn split(generics: &syn::Generics) -> (TokenStream, TokenStream, TokenStream) {
    let (impl_g, ty_g, where_c) = generics.split_for_impl();
    (quote!(#impl_g), quote!(#ty_g), quote!(#where_c))
}

/// Encode a `syn::Generics` back to `(generics_tokens, where_tokens)` strings
/// for storage in `TypeEntry`.
fn encode_generics(g: &syn::Generics) -> (String, String) {
    let params = &g.params;
    let generics_str = if params.is_empty() {
        String::new()
    } else {
        quote!(<#params>).to_string()
    };
    let where_str = g
        .where_clause
        .as_ref()
        .map(|wc| quote!(#wc).to_string())
        .unwrap_or_default();
    (generics_str, where_str)
}

/// Build the source type as it appears in an `impl` block:
/// `SourceIdent<ty_args>`.
///
/// - If the user supplied explicit ty_args on the source node, use them.
/// - Otherwise, use the target's `ty_generics` (appropriate for unary ops
///   where source and target share the same type params).
fn source_type(
    ident: &Ident,
    explicit_ty_args: Option<&TokenStream>,
    fallback_ty_g: &TokenStream,
) -> TokenStream {
    match explicit_ty_args {
        Some(args) => quote!(#ident #args),
        None => quote!(#ident #fallback_ty_g),
    }
}

// ---------------------------------------------------------------------------
// Public entry points
// ---------------------------------------------------------------------------

pub fn expand_shape(input: ShapeInput) -> TokenStream {
    let attrs = input.attrs;
    let target = input.target;
    let target_generics = input.target_generics;
    let hint = target.to_string();
    let mut acc: Vec<TokenStream> = Vec::new();

    let result = expand_expr(input.expr, &attrs, target, &target_generics, false, &hint, &mut acc);

    match result {
        Ok(main_ts) => {
            let mut output = TokenStream::new();
            for ts in acc {
                output.extend(ts);
            }
            output.extend(main_ts);
            output
        }
        Err(ts) => ts,
    }
}

pub fn register_typeshaper(input: DeriveInput) -> TokenStream {
    let file = crate_key();
    let type_name = input.ident.to_string();
    let entry = match extract_type_entry(&input) {
        Ok(e) => e,
        Err(e) => return e,
    };
    register(file, type_name, entry);
    quote! { #input }
}

pub fn register_typeshaper_export(input: DeriveInput) -> TokenStream {
    match try_register_typeshaper_export(input) {
        Ok(ts) => ts,
        Err(ts) => ts,
    }
}

fn try_register_typeshaper_export(input: DeriveInput) -> R {
    let type_ident = &input.ident;
    let file = crate_key();
    let type_name = type_ident.to_string();

    let entry = extract_type_entry(&input)?;

    register(file, type_name.clone(), entry.clone());
    register_exported(type_name, entry.clone());

    let macro_name = format!("typeshaper_import_{}", type_ident);
    let macro_ident: Ident = syn::parse_str(&macro_name).map_err(|e| {
        syn::Error::new(
            type_ident.span(),
            format!("typeshaper: cannot form macro name `{}`: {}", macro_name, e),
        )
        .to_compile_error()
    })?;

    // Encode generics and where clause as bracket-wrapped token groups.
    // Format: `__typeshaper_import!(TypeName, [<generics>], [where ...], fields...)`
    let generics_ts: TokenStream = entry.generics_tokens.parse().map_err(|e| {
        syn::Error::new(
            proc_macro2::Span::call_site(),
            format!(
                "typeshaper: failed to re-parse generics tokens `{}`: {}",
                entry.generics_tokens, e
            ),
        )
        .to_compile_error()
    })?;
    let where_ts: TokenStream = entry.where_tokens.parse().map_err(|e| {
        syn::Error::new(
            proc_macro2::Span::call_site(),
            format!(
                "typeshaper: failed to re-parse where tokens `{}`: {}",
                entry.where_tokens, e
            ),
        )
        .to_compile_error()
    })?;

    let field_entries: Vec<TokenStream> = entry
        .fields
        .iter()
        .map(|f| -> R {
            let fname: Ident = syn::parse_str(&f.name).map_err(|e| {
                syn::Error::new(
                    proc_macro2::Span::call_site(),
                    format!("typeshaper: invalid field name `{}`: {}", f.name, e),
                )
                .to_compile_error()
            })?;
            let ftype: TokenStream = f.ty_tokens.parse().map_err(|e| {
                syn::Error::new(
                    proc_macro2::Span::call_site(),
                    format!("typeshaper: invalid type tokens `{}`: {}", f.ty_tokens, e),
                )
                .to_compile_error()
            })?;
            let fvis: TokenStream = f.vis.parse().map_err(|e| {
                syn::Error::new(
                    proc_macro2::Span::call_site(),
                    format!("typeshaper: invalid visibility `{}`: {}", f.vis, e),
                )
                .to_compile_error()
            })?;
            if let Some(ref inner) = f.unwrapped_ty {
                let inner_ts: TokenStream = inner.parse().map_err(|e| {
                    syn::Error::new(
                        proc_macro2::Span::call_site(),
                        format!("typeshaper: invalid inner type `{}`: {}", inner, e),
                    )
                    .to_compile_error()
                })?;
                Ok(quote! { #fvis #fname : #ftype [#inner_ts] })
            } else {
                Ok(quote! { #fvis #fname : #ftype })
            }
        })
        .collect::<Result<Vec<_>, _>>()?;

    Ok(quote! {
        #input

        #[macro_export]
        macro_rules! #macro_ident {
            () => {
                ::typeshaper::__typeshaper_import!(
                    #type_ident,
                    [#generics_ts],
                    [#where_ts],
                    #(#field_entries),*
                );
            };
        }
    })
}

/// Consume the output of `__typeshaper_import!`: parse inline field tokens
/// (plus generics/where metadata) and register the type in the import namespace.
pub fn expand_import(input: ImportInput) -> TokenStream {
    let type_name = input.type_name.to_string();

    // Decode generics/where from the bracket groups.
    let generics_tokens = input.generics_tokens.to_string();
    let where_tokens = input.where_tokens.to_string();

    let fields: Vec<FieldDef> = input
        .fields
        .iter()
        .map(|(name, ty, unwrapped, vis)| {
            let vis_str = vis.to_string();
            if let Some(inner) = unwrapped {
                FieldDef::wrapped_optional(name.to_string(), vis_str, inner.to_string())
            } else {
                FieldDef::plain(name.to_string(), vis_str, ty.to_string())
            }
        })
        .collect();

    let entry = TypeEntry::with_generics(fields, generics_tokens, where_tokens);
    register(None, type_name, entry);
    TokenStream::new()
}

// ---------------------------------------------------------------------------
// Recursive helpers
// ---------------------------------------------------------------------------

fn expand_expr(
    expr: ShapeExpr,
    attrs: &[Attribute],
    target: Ident,
    target_generics: &syn::Generics,
    allow_inherit: bool,
    hint: &str,
    acc: &mut Vec<TokenStream>,
) -> Result<TokenStream, TokenStream> {
    match expr {
        ShapeExpr::Rebuild { source } => {
            let (src_ident, src_ty_args) = expand_node(source, hint, acc)?;
            rebuild(attrs, target, target_generics, allow_inherit, src_ident, src_ty_args)
        }
        ShapeExpr::Omit { source, fields } => {
            let (src_ident, src_ty_args) = expand_node(source, hint, acc)?;
            omit(attrs, target, target_generics, allow_inherit, src_ident, src_ty_args, fields)
        }
        ShapeExpr::Pick { source, fields } => {
            let (src_ident, src_ty_args) = expand_node(source, hint, acc)?;
            pick(attrs, target, target_generics, allow_inherit, src_ident, src_ty_args, fields)
        }
        ShapeExpr::Merge { left, right } => {
            let (left_ident, left_ty_args) = expand_node(left, hint, acc)?;
            let (right_ident, right_ty_args) = expand_node(right, hint, acc)?;
            merge(attrs, target, target_generics, allow_inherit, left_ident, left_ty_args, right_ident, right_ty_args)
        }
        ShapeExpr::Partial { source } => {
            let (src_ident, src_ty_args) = expand_node(source, hint, acc)?;
            partial(attrs, target, target_generics, allow_inherit, src_ident, src_ty_args)
        }
        ShapeExpr::Required { source } => {
            let (src_ident, src_ty_args) = expand_node(source, hint, acc)?;
            required(attrs, target, target_generics, allow_inherit, src_ident, src_ty_args)
        }
        ShapeExpr::Diff { left, right } => {
            let (left_ident, left_ty_args) = expand_node(left, hint, acc)?;
            let (right_ident, _) = expand_node(right, hint, acc)?;
            diff(attrs, target, target_generics, allow_inherit, left_ident, left_ty_args, right_ident)
        }
    }
}

/// Resolve a `ShapeNode` to `(concrete_ident, optional_explicit_ty_args)`.
///
/// - Leaf returns its ident and explicit ty_args directly.
/// - Composed generates an anonymous type (always with auto-inherited generics)
///   and returns its ident with no explicit ty_args.
fn expand_node(
    node: ShapeNode,
    hint: &str,
    acc: &mut Vec<TokenStream>,
) -> Result<(Ident, Option<TokenStream>), TokenStream> {
    match node {
        ShapeNode::Leaf(ident, ty_args) => Ok((ident, ty_args)),
        ShapeNode::Composed(expr) => {
            let id = next_anon_id();
            let anon_name = format!("__TypeshaperAnon_{}_{}", hint, id);
            let anon_ident: Ident = syn::parse_str(&anon_name).map_err(|e| {
                syn::Error::new(
                    proc_macro2::Span::call_site(),
                    format!(
                        "typeshaper: internal error generating anonymous type `{}`: {}",
                        anon_name, e
                    ),
                )
                .to_compile_error()
            })?;
            // Anonymous intermediates always allow generic auto-inherit (no user-specified ones).
            let ts = expand_expr(
                *expr,
                &[],
                anon_ident.clone(),
                &syn::Generics::default(),
                true,
                hint,
                acc,
            )?;
            acc.push(ts);
            Ok((anon_ident, None))
        }
    }
}

// ---------------------------------------------------------------------------
// T  →  Rebuild
// ---------------------------------------------------------------------------

type R = Result<TokenStream, TokenStream>;

fn rebuild(
    attrs: &[Attribute],
    target: Ident,
    target_generics: &syn::Generics,
    allow_inherit: bool,
    source: Ident,
    source_ty_args: Option<TokenStream>,
) -> R {
    let src_entry = try_lookup(&source)?;
    if !allow_inherit {
        if let Some(err) = check_no_implicit_generics(&source, &src_entry, target_generics) {
            return Err(err);
        }
    }
    let (names, types, vises) = to_token_vecs(&src_entry.fields)?;

    let eff_gen = effective_generics(target_generics, &src_entry, allow_inherit);
    let (impl_g, ty_g, where_c) = split(&eff_gen);
    let src_type = source_type(&source, source_ty_args.as_ref(), &ty_g);

    let (gen_str, where_str) = encode_generics(&eff_gen);
    register(
        crate_key(),
        target.to_string(),
        TypeEntry::with_generics(src_entry.fields, gen_str, where_str),
    );

    Ok(quote! {
        #(#attrs)*
        pub struct #target #impl_g #where_c {
            #(#vises #names: #types,)*
        }

        impl #impl_g ::typeshaper::TypeshaperInto<#target #ty_g> for #src_type #where_c {
            fn typeshaper_into(self) -> #target #ty_g {
                #target { #(#names: self.#names,)* }
            }
        }
    })
}

// ---------------------------------------------------------------------------
// T - [fields]  →  Omit
// ---------------------------------------------------------------------------

fn omit(
    attrs: &[Attribute],
    target: Ident,
    target_generics: &syn::Generics,
    allow_inherit: bool,
    source: Ident,
    source_ty_args: Option<TokenStream>,
    omit_fields: Vec<Ident>,
) -> R {
    let src_entry = try_lookup(&source)?;
    if !allow_inherit {
        if let Some(err) = check_no_implicit_generics(&source, &src_entry, target_generics) {
            return Err(err);
        }
    }

    // H-3: reject empty omit list
    if omit_fields.is_empty() {
        return Err(syn::Error::new(
            proc_macro2::Span::call_site(),
            "omit field list must not be empty; use `T` (Rebuild) to copy all fields",
        )
        .to_compile_error());
    }

    // B-2: check for duplicate fields and non-existent fields
    let mut seen = std::collections::HashSet::new();
    for f in &omit_fields {
        let name = f.to_string();
        if !seen.insert(name.clone()) {
            return Err(syn::Error::new(
                f.span(),
                format!("field `{}` is listed more than once in the omit list", name),
            )
            .to_compile_error());
        }
        if !src_entry.fields.iter().any(|d| d.name == name) {
            return Err(field_not_found(f, &source));
        }
    }
    let omit_set = seen;

    let kept: Vec<FieldDef> = src_entry
        .fields
        .into_iter()
        .filter(|f| !omit_set.contains(&f.name))
        .collect();
    let (names, types, vises) = to_token_vecs(&kept)?;

    let eff_gen = {
        let src_for_inherit = TypeEntry::with_generics(
            kept.clone(),
            src_entry.generics_tokens.clone(),
            src_entry.where_tokens.clone(),
        );
        effective_generics(target_generics, &src_for_inherit, allow_inherit)
    };
    let (impl_g, ty_g, where_c) = split(&eff_gen);
    let src_type = source_type(&source, source_ty_args.as_ref(), &ty_g);

    let (gen_str, where_str) = encode_generics(&eff_gen);
    register(
        crate_key(),
        target.to_string(),
        TypeEntry::with_generics(kept, gen_str, where_str),
    );

    Ok(quote! {
        #(#attrs)*
        pub struct #target #impl_g #where_c {
            #(#vises #names: #types,)*
        }

        impl #impl_g ::typeshaper::TypeshaperInto<#target #ty_g> for #src_type #where_c {
            fn typeshaper_into(self) -> #target #ty_g {
                #target { #(#names: self.#names,)* }
            }
        }
    })
}

// ---------------------------------------------------------------------------
// T & [fields]  →  Pick
// ---------------------------------------------------------------------------

fn pick(
    attrs: &[Attribute],
    target: Ident,
    target_generics: &syn::Generics,
    allow_inherit: bool,
    source: Ident,
    source_ty_args: Option<TokenStream>,
    pick_fields: Vec<Ident>,
) -> R {
    let src_entry = try_lookup(&source)?;
    if !allow_inherit {
        if let Some(err) = check_no_implicit_generics(&source, &src_entry, target_generics) {
            return Err(err);
        }
    }

    // H-3: reject empty pick list
    if pick_fields.is_empty() {
        return Err(syn::Error::new(
            proc_macro2::Span::call_site(),
            "pick field list must not be empty; use `T` (Rebuild) to copy all fields",
        )
        .to_compile_error());
    }

    let mut seen = std::collections::HashSet::new();
    let mut kept: Vec<FieldDef> = Vec::new();
    for f in &pick_fields {
        let name = f.to_string();
        if !seen.insert(name.clone()) {
            return Err(syn::Error::new(
                f.span(),
                format!("field `{}` is listed more than once in the pick list", name),
            )
            .to_compile_error());
        }
        match src_entry.fields.iter().find(|d| d.name == name) {
            Some(d) => kept.push(d.clone()),
            None => return Err(field_not_found(f, &source)),
        }
    }

    let (names, types, vises) = to_token_vecs(&kept)?;
    let eff_gen = {
        let src_for_inherit = TypeEntry::with_generics(
            kept.clone(),
            src_entry.generics_tokens.clone(),
            src_entry.where_tokens.clone(),
        );
        effective_generics(target_generics, &src_for_inherit, allow_inherit)
    };
    let (impl_g, ty_g, where_c) = split(&eff_gen);
    let src_type = source_type(&source, source_ty_args.as_ref(), &ty_g);

    let (gen_str, where_str) = encode_generics(&eff_gen);
    register(
        crate_key(),
        target.to_string(),
        TypeEntry::with_generics(kept, gen_str, where_str),
    );

    Ok(quote! {
        #(#attrs)*
        pub struct #target #impl_g #where_c {
            #(#vises #names: #types,)*
        }

        impl #impl_g ::typeshaper::TypeshaperInto<#target #ty_g> for #src_type #where_c {
            fn typeshaper_into(self) -> #target #ty_g {
                #target { #(#names: self.#names,)* }
            }
        }
    })
}

// ---------------------------------------------------------------------------
// A + B  →  Merge
// ---------------------------------------------------------------------------

fn merge(
    attrs: &[Attribute],
    target: Ident,
    target_generics: &syn::Generics,
    allow_inherit: bool,
    left: Ident,
    left_ty_args: Option<TokenStream>,
    right: Ident,
    right_ty_args: Option<TokenStream>,
) -> R {
    let entry_a = try_lookup(&left)?;
    let entry_b = try_lookup(&right)?;
    if !allow_inherit {
        // For merge, error if EITHER source is generic and target has no explicit params.
        if (entry_a.is_generic() || entry_b.is_generic())
            && target_generics.params.is_empty()
            && target_generics.where_clause.is_none()
        {
            let offender = if entry_a.is_generic() { &left } else { &right };
            let offender_entry = if entry_a.is_generic() { &entry_a } else { &entry_b };
            if let Some(err) =
                check_no_implicit_generics(offender, offender_entry, target_generics)
            {
                return Err(err);
            }
        }
    }

    let names_a_set: std::collections::HashSet<&str> =
        entry_a.fields.iter().map(|f| f.name.as_str()).collect();
    for f in &entry_b.fields {
        if names_a_set.contains(f.name.as_str()) {
            return Err(syn::Error::new(
                right.span(),
                format!(
                    "field `{}` exists in both `{}` and `{}`",
                    f.name, left, right
                ),
            )
            .to_compile_error());
        }
    }

    let (names_a, types_a, vises_a) = to_token_vecs(&entry_a.fields)?;
    let (names_b, types_b, vises_b) = to_token_vecs(&entry_b.fields)?;

    // Target generics: use explicit if provided; otherwise merge both sources (allow_inherit only).
    let eff_gen = if !target_generics.params.is_empty() || target_generics.where_clause.is_some() {
        target_generics.clone()
    } else if allow_inherit {
        // Auto-merge both source generics (only for anonymous intermediates).
        // Uses syn-based deduplication to avoid <T, T> collisions (B-3).
        merge_generics(&entry_a, &entry_b)
    } else {
        syn::Generics::default()
    };
    let (impl_g, ty_g, where_c) = split(&eff_gen);

    // Source types in impl: use explicit ty_args or fall back to respective
    // registered ty_generics.
    let left_ty = match left_ty_args.as_ref() {
        Some(a) => quote!(#left #a),
        None => {
            let g = parse_stored_generics(&entry_a);
            let (_, tg, _) = g.split_for_impl();
            quote!(#left #tg)
        }
    };
    let right_ty = match right_ty_args.as_ref() {
        Some(a) => quote!(#right #a),
        None => {
            let g = parse_stored_generics(&entry_b);
            let (_, tg, _) = g.split_for_impl();
            quote!(#right #tg)
        }
    };

    let mut all_fields = entry_a.fields;
    all_fields.extend(entry_b.fields);
    let (gen_str, where_str) = encode_generics(&eff_gen);
    register(
        crate_key(),
        target.to_string(),
        TypeEntry::with_generics(all_fields, gen_str, where_str),
    );

    Ok(quote! {
        #(#attrs)*
        pub struct #target #impl_g #where_c {
            #(#vises_a #names_a: #types_a,)*
            #(#vises_b #names_b: #types_b,)*
        }

        impl #impl_g From<(#left_ty, #right_ty)> for #target #ty_g #where_c {
            fn from((a, b): (#left_ty, #right_ty)) -> Self {
                #target {
                    #(#names_a: a.#names_a,)*
                    #(#names_b: b.#names_b,)*
                }
            }
        }
    })
}

// ---------------------------------------------------------------------------
// T?  →  Partial
// ---------------------------------------------------------------------------

fn partial(
    attrs: &[Attribute],
    target: Ident,
    target_generics: &syn::Generics,
    allow_inherit: bool,
    source: Ident,
    source_ty_args: Option<TokenStream>,
) -> R {
    let src_entry = try_lookup(&source)?;
    if !allow_inherit {
        if let Some(err) = check_no_implicit_generics(&source, &src_entry, target_generics) {
            return Err(err);
        }
    }

    let mut opt_fields: Vec<FieldDef> = Vec::with_capacity(src_entry.fields.len());
    let mut already_opt: Vec<bool> = Vec::with_capacity(src_entry.fields.len());

    for f in &src_entry.fields {
        if f.unwrapped_ty.is_some() {
            opt_fields.push(f.clone());
            already_opt.push(true);
        } else if let Some(inner) = try_unwrap_option(&f.ty_tokens) {
            opt_fields.push(FieldDef {
                name: f.name.clone(),
                vis: f.vis.clone(),
                ty_tokens: f.ty_tokens.clone(),
                unwrapped_ty: Some(inner),
            });
            already_opt.push(true);
        } else {
            opt_fields.push(FieldDef::wrapped_optional(
                f.name.clone(),
                f.vis.clone(),
                f.ty_tokens.clone(),
            ));
            already_opt.push(false);
        }
    }

    let (names, opt_types, vises) = to_token_vecs(&opt_fields)?;
    let eff_gen = {
        let src_for_inherit = TypeEntry::with_generics(
            opt_fields.clone(),
            src_entry.generics_tokens.clone(),
            src_entry.where_tokens.clone(),
        );
        effective_generics(target_generics, &src_for_inherit, allow_inherit)
    };
    let (impl_g, ty_g, where_c) = split(&eff_gen);
    let src_type = source_type(&source, source_ty_args.as_ref(), &ty_g);

    let (gen_str, where_str) = encode_generics(&eff_gen);
    register(
        crate_key(),
        target.to_string(),
        TypeEntry::with_generics(opt_fields, gen_str, where_str),
    );

    let from_exprs: Vec<TokenStream> = names
        .iter()
        .zip(already_opt.iter())
        .map(|(name, &already)| {
            if already {
                quote! { #name: src.#name }
            } else {
                quote! { #name: Some(src.#name) }
            }
        })
        .collect();

    Ok(quote! {
        #(#attrs)*
        pub struct #target #impl_g #where_c {
            #(#vises #names: #opt_types,)*
        }

        impl #impl_g From<#src_type> for #target #ty_g #where_c {
            fn from(src: #src_type) -> Self {
                #target { #(#from_exprs,)* }
            }
        }
    })
}

// ---------------------------------------------------------------------------
// T!  →  Required
// ---------------------------------------------------------------------------

fn try_unwrap_option(ty_tokens: &str) -> Option<String> {
    let ty: syn::Type = syn::parse_str(ty_tokens).ok()?;
    if let syn::Type::Path(tp) = ty {
        if tp.qself.is_some() {
            return None;
        }
        let segs: Vec<_> = tp.path.segments.iter().collect();
        let is_std_option = match segs.as_slice() {
            [s] if s.ident == "Option" => true,
            [a, b, c]
                if (a.ident == "std" || a.ident == "core")
                    && b.ident == "option"
                    && c.ident == "Option" =>
            {
                true
            }
            _ => false,
        };
        if !is_std_option {
            return None;
        }
        let last = segs.last()?;
        if let syn::PathArguments::AngleBracketed(ref args) = last.arguments {
            if args.args.len() == 1 {
                if let syn::GenericArgument::Type(inner) = &args.args[0] {
                    return Some(quote!(#inner).to_string());
                }
            }
        }
    }
    None
}

fn required(
    attrs: &[Attribute],
    target: Ident,
    target_generics: &syn::Generics,
    allow_inherit: bool,
    source: Ident,
    source_ty_args: Option<TokenStream>,
) -> R {
    let src_entry = try_lookup(&source)?;
    if !allow_inherit {
        if let Some(err) = check_no_implicit_generics(&source, &src_entry, target_generics) {
            return Err(err);
        }
    }

    let inner_fields: Vec<FieldDef> = src_entry
        .fields
        .iter()
        .map(|f| {
            let inner_ty = f
                .unwrapped_ty
                .clone()
                .or_else(|| try_unwrap_option(&f.ty_tokens));
            match inner_ty {
                Some(inner) => FieldDef::plain(f.name.clone(), f.vis.clone(), inner),
                None => f.clone(),
            }
        })
        .collect();

    let needs_unwrap: Vec<bool> = src_entry
        .fields
        .iter()
        .map(|f| f.unwrapped_ty.is_some() || try_unwrap_option(&f.ty_tokens).is_some())
        .collect();

    let (names, inner_types, vises) = to_token_vecs(&inner_fields)?;
    let eff_gen = {
        let src_for_inherit = TypeEntry::with_generics(
            inner_fields.clone(),
            src_entry.generics_tokens.clone(),
            src_entry.where_tokens.clone(),
        );
        effective_generics(target_generics, &src_for_inherit, allow_inherit)
    };
    let (impl_g, ty_g, where_c) = split(&eff_gen);
    let src_type = source_type(&source, source_ty_args.as_ref(), &ty_g);

    let (gen_str, where_str) = encode_generics(&eff_gen);
    register(
        crate_key(),
        target.to_string(),
        TypeEntry::with_generics(inner_fields, gen_str, where_str),
    );

    let any_needs_unwrap = needs_unwrap.iter().any(|&b| b);

    if any_needs_unwrap {
        let try_from_exprs: Vec<TokenStream> = names
            .iter()
            .zip(needs_unwrap.iter())
            .map(|(name, &unwrap)| {
                if unwrap {
                    quote! {
                        #name: src.#name.ok_or(
                            ::typeshaper::RequiredError::new(stringify!(#name))
                        )?
                    }
                } else {
                    quote! { #name: src.#name }
                }
            })
            .collect();

        Ok(quote! {
            #(#attrs)*
            pub struct #target #impl_g #where_c {
                #(#vises #names: #inner_types,)*
            }

            impl #impl_g TryFrom<#src_type> for #target #ty_g #where_c {
                type Error = ::typeshaper::RequiredError;

                fn try_from(src: #src_type) -> Result<Self, Self::Error> {
                    Ok(Self { #(#try_from_exprs,)* })
                }
            }
        })
    } else {
        Ok(quote! {
            #(#attrs)*
            pub struct #target #impl_g #where_c {
                #(#vises #names: #inner_types,)*
            }

            impl #impl_g From<#src_type> for #target #ty_g #where_c {
                fn from(src: #src_type) -> Self {
                    Self { #(#names: src.#names,)* }
                }
            }
        })
    }
}

// ---------------------------------------------------------------------------
// A % B  →  Diff
// ---------------------------------------------------------------------------

fn diff(
    attrs: &[Attribute],
    target: Ident,
    target_generics: &syn::Generics,
    allow_inherit: bool,
    left: Ident,
    left_ty_args: Option<TokenStream>,
    right: Ident,
) -> R {
    let entry_a = try_lookup(&left)?;
    let entry_b = try_lookup(&right)?;
    if !allow_inherit {
        if let Some(err) = check_no_implicit_generics(&left, &entry_a, target_generics) {
            return Err(err);
        }
    }

    let kept: Vec<FieldDef> = entry_a
        .fields
        .clone()
        .into_iter()
        .filter(|f| {
            !entry_b.fields.iter().any(|fb| {
                fb.name == f.name
                    && normalize_ty(&fb.ty_tokens) == normalize_ty(&f.ty_tokens)
            })
        })
        .collect();

    if kept.is_empty() {
        return Err(syn::Error::new(
            left.span(),
            format!("`{}` has no fields that are absent from `{}`", left, right),
        )
        .to_compile_error());
    }

    let (names, types, vises) = to_token_vecs(&kept)?;
    // Diff inherits left source's generics.
    let eff_gen = {
        let src_for_inherit = TypeEntry::with_generics(
            kept.clone(),
            entry_a.generics_tokens.clone(),
            entry_a.where_tokens.clone(),
        );
        effective_generics(target_generics, &src_for_inherit, allow_inherit)
    };
    let (impl_g, ty_g, where_c) = split(&eff_gen);
    let left_type = source_type(&left, left_ty_args.as_ref(), &ty_g);

    let (gen_str, where_str) = encode_generics(&eff_gen);
    register(
        crate_key(),
        target.to_string(),
        TypeEntry::with_generics(kept, gen_str, where_str),
    );

    Ok(quote! {
        #(#attrs)*
        pub struct #target #impl_g #where_c {
            #(#vises #names: #types,)*
        }

        impl #impl_g ::typeshaper::TypeshaperInto<#target #ty_g> for #left_type #where_c {
            fn typeshaper_into(self) -> #target #ty_g {
                #target { #(#names: self.#names,)* }
            }
        }
    })
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

fn normalize_ty(ty_tokens: &str) -> String {
    syn::parse_str::<syn::Type>(ty_tokens)
        .map(|ty| quote!(#ty).to_string())
        .unwrap_or_else(|_| ty_tokens.to_owned())
}

fn try_lookup(ident: &Ident) -> Result<TypeEntry, TokenStream> {
    let file = crate_key();
    let name = ident.to_string();
    if let Some(entry) = lookup(file, &name) {
        return Ok(entry);
    }
    if let Some(entry) = lookup(None, &name) {
        return Ok(entry);
    }
    if let Some(entry) = lookup_exported(&name) {
        return Ok(entry);
    }
    Err(syn::Error::new(
        ident.span(),
        format!(
            "type `{}` is not registered — \
             apply `#[typeshaper]` to it, or create it with `typex!()` first",
            ident
        ),
    )
    .to_compile_error())
}

fn field_not_found(field: &Ident, source: &Ident) -> TokenStream {
    syn::Error::new(
        field.span(),
        format!("field `{}` does not exist on `{}`", field, source),
    )
    .to_compile_error()
}

fn extract_type_entry(input: &DeriveInput) -> Result<TypeEntry, TokenStream> {
    let fields = match &input.data {
        Data::Struct(data) => match &data.fields {
            Fields::Named(named) => named
                .named
                .iter()
                .filter_map(|f| {
                    f.ident.as_ref().map(|ident| {
                        let ty = &f.ty;
                        let vis = &f.vis;
                        FieldDef::plain(
                            ident.to_string(),
                            quote!(#vis).to_string(),
                            quote!(#ty).to_string(),
                        )
                    })
                })
                .collect(),
            _ => {
                return Err(syn::Error::new_spanned(
                    &input.ident,
                    "#[typeshaper] only supports structs with named fields",
                )
                .to_compile_error())
            }
        },
        _ => {
            return Err(syn::Error::new_spanned(
                &input.ident,
                "#[typeshaper] only supports structs",
            )
            .to_compile_error())
        }
    };

    let params = &input.generics.params;
    let generics_tokens = if params.is_empty() {
        String::new()
    } else {
        quote!(<#params>).to_string()
    };
    let where_tokens = input
        .generics
        .where_clause
        .as_ref()
        .map(|wc| quote!(#wc).to_string())
        .unwrap_or_default();

    Ok(TypeEntry::with_generics(fields, generics_tokens, where_tokens))
}

/// Returns a stable string identifier for a generic parameter, used for deduplication.
fn generic_param_ident(p: &syn::GenericParam) -> String {
    match p {
        syn::GenericParam::Type(t) => t.ident.to_string(),
        syn::GenericParam::Lifetime(l) => l.lifetime.ident.to_string(),
        syn::GenericParam::Const(c) => c.ident.to_string(),
    }
}

/// Merge the generic parameters of two `TypeEntry`s into a single `syn::Generics`,
/// deduplicating by parameter identifier (prevents `<T, T>` when both sources share
/// the same type variable).
///
/// Where-clause predicates from both sides are combined without deduplication
/// (identical predicates are harmless; de-duplicating them would require deeper
/// semantic comparison).
fn merge_generics(entry_a: &TypeEntry, entry_b: &TypeEntry) -> syn::Generics {
    let g_a = parse_stored_generics(entry_a);
    let g_b = parse_stored_generics(entry_b);

    let existing: std::collections::HashSet<String> =
        g_a.params.iter().map(generic_param_ident).collect();

    let mut merged = g_a;
    for param in g_b.params {
        if !existing.contains(&generic_param_ident(&param)) {
            merged.params.push(param);
        }
    }
    if let Some(wc_b) = g_b.where_clause {
        merged.make_where_clause().predicates.extend(wc_b.predicates);
    }
    merged
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse::ImportInput;
    use quote::quote;

    #[test]
    fn issue1_import_preserves_field_visibility() {
        let input = ImportInput {
            type_name: syn::parse_str("__BugIssue1_VisLoss").unwrap(),
            generics_tokens: TokenStream::new(),
            where_tokens: TokenStream::new(),
            fields: vec![
                (
                    syn::parse_str("id").unwrap(),
                    quote! { u64 },
                    None,
                    quote! { pub },
                ),
                (
                    syn::parse_str("secret").unwrap(),
                    quote! { String },
                    None,
                    quote! {},
                ),
            ],
        };

        expand_import(input);

        let entry = crate::state::lookup(None, "__BugIssue1_VisLoss")
            .expect("expand_import 应将类型注册到 None 命名空间");

        let id_vis = &entry.fields.iter().find(|f| f.name == "id").unwrap().vis;
        let secret_vis = &entry.fields.iter().find(|f| f.name == "secret").unwrap().vis;
        assert_eq!(id_vis, "pub");
        assert_eq!(secret_vis, "");
    }

    #[test]
    fn merge_generics_both_empty() {
        let a = TypeEntry::plain(vec![]);
        let b = TypeEntry::plain(vec![]);
        let merged = merge_generics(&a, &b);
        assert!(merged.params.is_empty(), "both empty → no params");
        assert!(merged.where_clause.is_none());
    }

    #[test]
    fn merge_generics_one_empty() {
        let a = TypeEntry::with_generics(vec![], "< T >".into(), "".into());
        let b = TypeEntry::plain(vec![]);
        let merged_ab = merge_generics(&a, &b);
        assert_eq!(merged_ab.params.len(), 1, "one generic + empty → 1 param");

        let merged_ba = merge_generics(&b, &a);
        assert_eq!(merged_ba.params.len(), 1, "empty + one generic → 1 param");
    }

    #[test]
    fn merge_generics_different_params() {
        let a = TypeEntry::with_generics(vec![], "< T >".into(), "".into());
        let b = TypeEntry::with_generics(vec![], "< U >".into(), "".into());
        let merged = merge_generics(&a, &b);
        assert_eq!(merged.params.len(), 2, "T + U → 2 params");
        let names: Vec<String> = merged.params.iter().map(generic_param_ident).collect();
        assert!(names.contains(&"T".to_string()), "T must be present");
        assert!(names.contains(&"U".to_string()), "U must be present");
    }

    #[test]
    fn merge_generics_deduplicates_same_param() {
        let a = TypeEntry::with_generics(vec![], "< T >".into(), "".into());
        let b = TypeEntry::with_generics(vec![], "< T >".into(), "".into());
        let merged = merge_generics(&a, &b);
        assert_eq!(merged.params.len(), 1, "same param T in both → deduplicated to 1");
        assert_eq!(generic_param_ident(&merged.params[0]), "T");
    }

    #[test]
    fn merge_generics_combines_where_clauses() {
        let a = TypeEntry::with_generics(vec![], "< T >".into(), "where T : Clone".into());
        let b = TypeEntry::with_generics(vec![], "< U >".into(), "where U : Debug".into());
        let merged = merge_generics(&a, &b);
        let wc = merged.where_clause.expect("should have where clause");
        assert_eq!(wc.predicates.len(), 2, "two predicates from both sides");
    }
}

fn to_token_vecs(
    fields: &[FieldDef],
) -> Result<(Vec<Ident>, Vec<TokenStream>, Vec<TokenStream>), TokenStream> {
    let mut names = Vec::with_capacity(fields.len());
    let mut types = Vec::with_capacity(fields.len());
    let mut vises = Vec::with_capacity(fields.len());
    for f in fields {
        let ident = syn::parse_str::<Ident>(&f.name).map_err(|e| {
            syn::Error::new(
                proc_macro2::Span::call_site(),
                format!("typeshaper: invalid field name `{}`: {}", f.name, e),
            )
            .to_compile_error()
        })?;
        let ty = f.ty_tokens.parse::<TokenStream>().map_err(|e| {
            syn::Error::new(
                proc_macro2::Span::call_site(),
                format!("typeshaper: invalid type string `{}`: {}", f.ty_tokens, e),
            )
            .to_compile_error()
        })?;
        let vis: TokenStream = f.vis.parse().map_err(|e| {
            syn::Error::new(
                proc_macro2::Span::call_site(),
                format!("typeshaper: invalid visibility `{}`: {}", f.vis, e),
            )
            .to_compile_error()
        })?;
        names.push(ident);
        types.push(ty);
        vises.push(vis);
    }
    Ok((names, types, vises))
}
