use once_cell::sync::Lazy;
use std::collections::HashMap;
use std::sync::Mutex;
use std::sync::atomic::{AtomicUsize, Ordering};

/// Registry key: `(crate_manifest_dir, type_name)`.
///
/// `CARGO_MANIFEST_DIR` is unique per crate, so this prevents identically-named
/// types from different crates colliding in the shared proc-macro registry — a
/// critical property when rust-analyzer reuses a single proc-macro server for
/// the entire workspace.
///
/// `None` is used for the cross-crate import namespace (see [`register_import`])
/// and in unit-test contexts where the env-var is absent.
type RegKey = (Option<String>, String);

static ANON_COUNTER: AtomicUsize = AtomicUsize::new(0);

/// Returns a globally unique ID for anonymous intermediate types generated by
/// `expand_node`. Using a global counter avoids naming collisions when two
/// `shape!()` calls share the same target hint and both produce sub-expressions.
pub fn next_anon_id() -> usize {
    ANON_COUNTER.fetch_add(1, Ordering::Relaxed)
}

#[derive(Clone, Debug, PartialEq)]
pub struct FieldDef {
    pub name: String,
    /// Visibility modifier as a token string: `"pub"`, `"pub (crate)"`, `""` (private), etc.
    /// Inherited from the source field and reproduced verbatim in generated structs.
    pub vis: String,
    /// Type as it appears in the generated struct definition.
    pub ty_tokens: String,
    /// Present only when this field was wrapped in `Option<_>` by a `Partial`
    /// operation. Holds the inner (unwrapped) type so `Required` can restore it.
    pub unwrapped_ty: Option<String>,
}

impl FieldDef {
    pub fn plain(name: String, vis: String, ty_tokens: String) -> Self {
        Self {
            name,
            vis,
            ty_tokens,
            unwrapped_ty: None,
        }
    }

    /// Creates a field whose type is `Option<inner_ty>` and whose original
    /// visibility and inner type are preserved for `Required` to consume.
    pub fn wrapped_optional(name: String, vis: String, inner_ty: String) -> Self {
        let ty_tokens = format!("Option<{}>", inner_ty);
        Self {
            name,
            vis,
            ty_tokens,
            unwrapped_ty: Some(inner_ty),
        }
    }
}

/// Per-type registry entry: fields plus optional generic/lifetime/where-clause metadata.
///
/// The `generics_tokens` and `where_tokens` are stored as raw token strings so
/// they can cross macro-invocation boundaries inside the same compilation unit
/// (the proc-macro process keeps the global statics alive for the whole build).
/// They are re-parsed into `syn::Generics` only when code generation needs them.
#[derive(Clone, Debug, PartialEq)]
pub struct TypeEntry {
    pub fields: Vec<FieldDef>,
    /// Angle-bracket generic parameter list, e.g. `"< T : Clone + Display , 'a >"`.
    /// Empty string for non-generic types.
    pub generics_tokens: String,
    /// Where clause, e.g. `"where T : Debug"`.
    /// Empty string if absent.
    pub where_tokens: String,
}

impl TypeEntry {
    /// A plain, non-generic type entry.
    pub fn plain(fields: Vec<FieldDef>) -> Self {
        Self {
            fields,
            generics_tokens: String::new(),
            where_tokens: String::new(),
        }
    }

    /// A generic type entry.
    pub fn with_generics(
        fields: Vec<FieldDef>,
        generics_tokens: String,
        where_tokens: String,
    ) -> Self {
        Self { fields, generics_tokens, where_tokens }
    }

    pub fn is_generic(&self) -> bool {
        !self.generics_tokens.is_empty() || !self.where_tokens.is_empty()
    }
}

// ---------------------------------------------------------------------------
// Primary registry  (key = crate + type name)
// ---------------------------------------------------------------------------

static REGISTRY: Lazy<Mutex<HashMap<RegKey, TypeEntry>>> =
    Lazy::new(|| Mutex::new(HashMap::new()));

/// Registers `entry` under `(crate_dir, type_name)` in the primary registry.
///
/// Must **never panic** — a panic here would poison the global `Mutex` and
/// cause every subsequent macro invocation to fail with `PoisonError`.
/// Uses `unwrap_or_else(|e| e.into_inner())` to recover from a poisoned lock.
pub fn register(crate_dir: Option<String>, type_name: String, entry: TypeEntry) {
    REGISTRY
        .lock()
        .unwrap_or_else(|e| e.into_inner())
        .insert((crate_dir, type_name), entry);
}

/// Returns the registered `TypeEntry` for `(crate_dir, type_name)`, or `None`.
///
/// Uses poison-safe lock recovery for the same reason as [`register`].
pub fn lookup(crate_dir: Option<String>, type_name: &str) -> Option<TypeEntry> {
    REGISTRY
        .lock()
        .unwrap_or_else(|e| e.into_inner())
        .get(&(crate_dir, type_name.to_string()))
        .cloned()
}

// ---------------------------------------------------------------------------
// Cross-crate import namespace  (key = None in primary registry)
// ---------------------------------------------------------------------------

/// Registers a cross-crate import under the `None` key.
///
/// Called only by `expand_import` (via `__typeshaper_import!`).
/// Cross-crate imports do not carry generic metadata (the companion macro
/// format currently encodes only field names, types, and visibility).
pub fn register_import(type_name: String, fields: Vec<FieldDef>) {
    register(None, type_name, TypeEntry::plain(fields));
}

// ---------------------------------------------------------------------------
// Export registry  (key = type name only)
// ---------------------------------------------------------------------------

static EXPORT_REGISTRY: Lazy<Mutex<HashMap<String, TypeEntry>>> =
    Lazy::new(|| Mutex::new(HashMap::new()));

/// Write `entry` into the export registry under `type_name`.
///
/// Called only by `register_typeshaper_export`; never called by `#[typeshaper]`.
pub fn register_exported(type_name: String, entry: TypeEntry) {
    EXPORT_REGISTRY
        .lock()
        .unwrap_or_else(|e| e.into_inner())
        .insert(type_name, entry);
}

/// Look up `type_name` in the export registry (last-resort cross-crate fallback).
pub fn lookup_exported(type_name: &str) -> Option<TypeEntry> {
    EXPORT_REGISTRY
        .lock()
        .unwrap_or_else(|e| e.into_inner())
        .get(type_name)
        .cloned()
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // ── FieldDef constructors ────────────────────────────────────────────────

    #[test]
    fn wrapped_optional_no_extra_spaces_simple_type() {
        let f = FieldDef::wrapped_optional("x".into(), "pub".into(), "String".into());
        assert_eq!(f.ty_tokens, "Option<String>");
        assert_eq!(f.unwrapped_ty.as_deref(), Some("String"));
        assert_eq!(f.vis, "pub");
    }

    #[test]
    fn wrapped_optional_no_extra_spaces_generic_type() {
        // quote! serialises Vec<String> with spaces; wrapping must not add more
        let f = FieldDef::wrapped_optional("items".into(), "pub".into(), "Vec < String >".into());
        assert_eq!(f.ty_tokens, "Option<Vec < String >>");
        assert_eq!(f.unwrapped_ty.as_deref(), Some("Vec < String >"));
    }

    #[test]
    fn plain_field_has_no_unwrapped_ty() {
        let f = FieldDef::plain("id".into(), "pub".into(), "u64".into());
        assert_eq!(f.ty_tokens, "u64");
        assert_eq!(f.vis, "pub");
        assert!(f.unwrapped_ty.is_none());
    }

    #[test]
    fn field_vis_is_preserved() {
        let f = FieldDef::plain("x".into(), "pub (crate)".into(), "u32".into());
        assert_eq!(f.vis, "pub (crate)");
        let f2 = FieldDef::plain("y".into(), "".into(), "u32".into());
        assert_eq!(f2.vis, "");
    }

    // ── TypeEntry constructors ───────────────────────────────────────────────

    #[test]
    fn type_entry_plain_is_not_generic() {
        let entry = TypeEntry::plain(vec![FieldDef::plain("x".into(), "pub".into(), "u32".into())]);
        assert!(!entry.is_generic());
        assert_eq!(entry.generics_tokens, "");
        assert_eq!(entry.where_tokens, "");
    }

    #[test]
    fn type_entry_with_generics_is_generic() {
        let entry = TypeEntry::with_generics(
            vec![],
            "< T >".into(),
            "".into(),
        );
        assert!(entry.is_generic());
    }

    #[test]
    fn type_entry_where_only_is_generic() {
        let entry = TypeEntry::with_generics(vec![], "".into(), "where T : Clone".into());
        assert!(entry.is_generic());
    }

    // ── next_anon_id ─────────────────────────────────────────────────────────

    #[test]
    fn next_anon_id_is_monotonically_increasing() {
        let a = next_anon_id();
        let b = next_anon_id();
        let c = next_anon_id();
        assert!(b > a, "second id ({b}) must be greater than first ({a})");
        assert!(c > b, "third id ({c}) must be greater than second ({b})");
    }

    #[test]
    fn next_anon_id_never_repeats() {
        let ids: Vec<usize> = (0..16).map(|_| next_anon_id()).collect();
        let unique: std::collections::HashSet<_> = ids.iter().collect();
        assert_eq!(ids.len(), unique.len(), "all 16 ids must be unique");
    }

    // ── register / lookup ────────────────────────────────────────────────────

    #[test]
    fn register_is_idempotent_for_same_fields() {
        let fields = vec![
            FieldDef::plain("id".into(), "pub".into(), "u64".into()),
            FieldDef::plain("name".into(), "pub".into(), "String".into()),
        ];
        let entry = TypeEntry::plain(fields.clone());
        register(None, "__StateTest_Idempotent".into(), entry.clone());
        register(None, "__StateTest_Idempotent".into(), entry.clone());
        assert_eq!(lookup(None, "__StateTest_Idempotent").unwrap().fields, fields);
    }

    #[test]
    fn register_overwrites_on_different_fields_without_panicking() {
        let fields_b = vec![FieldDef::plain("name".into(), "pub".into(), "String".into())];
        register(None, "__StateTest_Overwrite".into(),
            TypeEntry::plain(vec![FieldDef::plain("id".into(), "pub".into(), "u64".into())]));
        register(None, "__StateTest_Overwrite".into(),
            TypeEntry::plain(fields_b.clone()));
        assert_eq!(lookup(None, "__StateTest_Overwrite").unwrap().fields, fields_b);
    }

    #[test]
    fn different_crates_same_name_do_not_collide() {
        let dir_a = Some("/workspace/crate_a".to_string());
        let dir_b = Some("/workspace/crate_b".to_string());
        let fields_a = vec![FieldDef::plain("x".into(), "pub".into(), "u32".into())];
        let fields_b = vec![FieldDef::plain("y".into(), "pub".into(), "String".into())];

        register(dir_a.clone(), "__StateTest_Scoped".into(), TypeEntry::plain(fields_a.clone()));
        register(dir_b.clone(), "__StateTest_Scoped".into(), TypeEntry::plain(fields_b.clone()));

        assert_eq!(lookup(dir_a, "__StateTest_Scoped").unwrap().fields, fields_a);
        assert_eq!(lookup(dir_b, "__StateTest_Scoped").unwrap().fields, fields_b);
    }

    #[test]
    fn lookup_returns_none_for_unknown_type() {
        assert!(lookup(None, "__StateTest_DoesNotExist").is_none());
    }

    #[test]
    fn lookup_returns_registered_fields() {
        let fields = vec![FieldDef::plain("score".into(), "pub".into(), "u32".into())];
        register(None, "__StateTest_Lookup".into(), TypeEntry::plain(fields.clone()));
        let got = lookup(None, "__StateTest_Lookup").expect("should be registered");
        assert_eq!(got.fields, fields);
    }

    #[test]
    fn register_preserves_generics_tokens() {
        let entry = TypeEntry::with_generics(
            vec![FieldDef::plain("val".into(), "pub".into(), "T".into())],
            "< T >".into(),
            "".into(),
        );
        register(None, "__StateTest_Generic".into(), entry.clone());
        let got = lookup(None, "__StateTest_Generic").unwrap();
        assert_eq!(got.generics_tokens, "< T >");
        assert_eq!(got.where_tokens, "");
    }

    #[test]
    fn register_preserves_where_tokens() {
        let entry = TypeEntry::with_generics(
            vec![FieldDef::plain("val".into(), "pub".into(), "T".into())],
            "< T >".into(),
            "where T : Clone".into(),
        );
        register(None, "__StateTest_Where".into(), entry);
        let got = lookup(None, "__StateTest_Where").unwrap();
        assert_eq!(got.where_tokens, "where T : Clone");
    }

    // ── cross-crate import namespace ─────────────────────────────────────────

    #[test]
    fn import_namespace_none_key_does_not_collide_with_local_key() {
        let local_dir = Some("/workspace/my_crate".to_string());
        let local_fields = vec![FieldDef::plain("age".into(), "pub".into(), "u8".into())];
        register(local_dir.clone(), "__StateTest_Import_User".into(),
            TypeEntry::plain(local_fields.clone()));

        let import_fields = vec![FieldDef::plain("role".into(), "pub".into(), "String".into())];
        register_import("__StateTest_Import_User".into(), import_fields.clone());

        assert_eq!(
            lookup(local_dir, "__StateTest_Import_User").unwrap().fields,
            local_fields
        );
        assert_eq!(
            lookup(None, "__StateTest_Import_User").unwrap().fields,
            import_fields
        );
    }

    // ── export registry ──────────────────────────────────────────────────────

    #[test]
    fn exported_type_is_found_by_lookup_exported() {
        let fields = vec![FieldDef::plain("role".into(), "pub".into(), "String".into())];
        register_exported("__StateTest_ExportedUser".into(), TypeEntry::plain(fields.clone()));
        assert_eq!(lookup_exported("__StateTest_ExportedUser").unwrap().fields, fields);
    }

    #[test]
    fn non_exported_type_is_not_in_export_registry() {
        register(
            Some("/crate_a".into()),
            "__StateTest_LocalOnly".into(),
            TypeEntry::plain(vec![FieldDef::plain("x".into(), "pub".into(), "u32".into())]),
        );
        assert!(lookup_exported("__StateTest_LocalOnly").is_none());
    }

    #[test]
    fn exported_type_does_not_collide_with_same_named_local_type() {
        let local_fields = vec![FieldDef::plain("age".into(), "pub".into(), "u8".into())];
        let export_fields = vec![FieldDef::plain("role".into(), "pub".into(), "String".into())];

        register(
            Some("/tests_crate".into()),
            "__StateTest_DualUser".into(),
            TypeEntry::plain(local_fields.clone()),
        );
        register_exported("__StateTest_DualUser".into(), TypeEntry::plain(export_fields.clone()));

        assert_eq!(
            lookup(Some("/tests_crate".into()), "__StateTest_DualUser").unwrap().fields,
            local_fields
        );
        assert_eq!(
            lookup_exported("__StateTest_DualUser").unwrap().fields,
            export_fields
        );
    }

    #[test]
    fn exported_type_preserves_generics() {
        let entry = TypeEntry::with_generics(
            vec![FieldDef::plain("val".into(), "pub".into(), "T".into())],
            "< T : Clone >".into(),
            "".into(),
        );
        register_exported("__StateTest_ExportedGeneric".into(), entry);
        let got = lookup_exported("__StateTest_ExportedGeneric").unwrap();
        assert_eq!(got.generics_tokens, "< T : Clone >");
    }
}
