use std::fmt;

/// Error returned by `TryFrom` implementations generated by `typex!(Target = T!)`.
///
/// Carries the name of the first `Option`-wrapped field that was `None` when
/// attempting to convert a `Partial` type back into its `Required` form.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RequiredError {
    /// Name of the field that was `None`.
    pub field: &'static str,
}

impl fmt::Display for RequiredError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "required field `{}` is None", self.field)
    }
}

impl std::error::Error for RequiredError {}
